<?php


/**
 * @file
 * Install, update, and uninstall functions for the Group context module.
 */

/**
 * Implements hook_uninstall().
 */
function og_context_uninstall() {
  $vars = array(
    'og_context_negotiation_group_context',
    'og_context_providers_weight_group_context',
  );
  foreach ($vars as $var) {
    // @FIXME
// // @FIXME
// // The correct configuration object could not be determined. You'll need to
// // rewrite this call manually.
// variable_del($var);

  }
}